### ISSUE TITLE
Twitter Bot (4/5) - Twitter Bot CLI - Tweet when issue is created

### ISSUE THREAD

**Issue by masonicGIT** [21hackers/git-money#125]
**Current Bounty: 23,925 bits / ~ $10** [Proof](https://live.blockcypher.com/btc/address/3PfUKcdBErfJdHbTh29rdgbep87KB1CnyK)
*Submit a pull request containing your bitcoin address that resolves this issue and automatically get paid the amount above if it's merged.*

**Bounty Details:**
Setup the github issue creator function to send out a tweet whenever a new issue is created

**Comment by hems** [comment]
You probably want to actually use Github Webhook and point it to a hosted script that will do that for you?

see more here:
https://developer.github.com/v3/activity/events/types/#issuesevent

People using git-money on their repositories would then be able to setup the hook, perhaps insecurely write their twitter API KEY as a GET parameter for that script.

The good side is that then even when a issue is created using the browser the twit will be created, also then you can have the hook to twit different things when the issue is closed, etcs.

Good luck with the project, it's a very cool one (( :

peace

**Comment by masonicGIT** [comment]
Closing - This feature has already been incorporated.
